### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by senSweat** [sy007/CalendarView#1]
BUG
跨月份选择时仍有部分间隔日期没有背景色

另有两处请教
一: 如何调节日期的高度？  现在的样子看起来很窄
二: 如何使选中的日期为圆角  中间的间隔日期为直角矩形？

**Comment by sy007** [comment]
> BUG
> 跨月份选择时仍有部分间隔日期没有背景色
> 
> 另有两处请教
> 一: 如何调节日期的高度？ 现在的样子看起来很窄
> 二: 如何使选中的日期为圆角 中间的间隔日期为直角矩形？


你好，**跨月份选择时仍有部分间隔日期没有背景色**BUG已修复。
另外关于第一个问题暂时可以通过一下三个属性设置
或者在CalendarAdapter#parseTypedArray#L 71修改高度

firstTopMargin | dimension | 节日距离顶部距离
-- | -- | --
secondTopMargin | dimension | 天距离节日底部距离
thirdTopMargin | dimension | 选中文案距离天底部距离

第二个问题
如何使选中的日期为圆角。 目前不支持，需要自己修改源码
中间的间隔日期为直角矩形。  这个可以通过**selectStyle** 属性设置

selectStyle | enum | 选中样式(rectangle 矩形 roundRectangle 圆角矩形)
-- | -- | --

**Comment by senSweat** [comment]
Thank U！


| |
周聪
邮箱：zhoucong_cd@163.com
|

签名由 网易邮箱大师 定制

On 06/04/2019 11:02, SunYuan wrote:

BUG
跨月份选择时仍有部分间隔日期没有背景色

另有两处请教
一: 如何调节日期的高度？ 现在的样子看起来很窄
二: 如何使选中的日期为圆角 中间的间隔日期为直角矩形？
你好，跨月份选择时仍有部分间隔日期没有背景色BUG已修复。
另外关于第一个问题暂时可以通过一下三个属性设置

| firstTopMargin | dimension | 节日距离顶部距离 |
| secondTopMargin | dimension | 天距离节日底部距离 |
| thirdTopMargin | dimension | 选中文案距离天底部距离 |

第二个问题
如何使选中的日期为圆角。 目前不支持，需要自己修改源码
中间的间隔日期为直角矩形。 这个可以通过selectStyle 属性设置

| selectStyle | enum | 选中样式(rectangle 矩形 roundRectangle 圆角矩形) |
