### ISSUE TITLE
关于日期自动选中的问题

### ISSUE THREAD

**Issue by helloShiTou11** [sy007/CalendarView#10]
作者您好：
       不知道您对这个库是否还有维护，我在使用日历的时候  修改了  calendar.add(Calendar.DATE, 25);
修改25数值为40 他会有一个默认选择是日期，可以帮忙排查一下嘛？

**Comment by sy007** [comment]
> 作者您好：
> 不知道您对这个库是否还有维护，我在使用日历的时候 修改了 calendar.add(Calendar.DATE, 25);
> 修改25数值为40 他会有一个默认选择是日期，可以帮忙排查一下嘛？

请问是单选模式还是多选模式，调用日历的代码是怎样的？“我在使用日历的时候 修改了 calendar.add(Calendar.DATE, 25);
修改25数值为40” 是在初始化时修改的吗？麻烦提供下代码片段以及详细描述。

**Comment by helloShiTou11** [comment]
是我这边的bug，我默认给月份+了2，谢谢作者。顺便问一下多选怎么实现下面的选中效果
![微信图片_20210701154648](https://user-images.githubusercontent.com/23192549/124086499-b0feed80-da83-11eb-9a6f-d0998cf0ae2c.jpg)

-

**Comment by sy007** [comment]
> 是我这边的bug，我默认给月份+了2，谢谢作者。顺便问一下多选怎么实现下面的选中效果
> ![微信图片_20210701154648](https://user-images.githubusercontent.com/23192549/124086499-b0feed80-da83-11eb-9a6f-d0998cf0ae2c.jpg)

如果完全做到这样的UI选中样式，那就要修改源码了。目前本库支持 选择范围样式，和两边选中的样式。 因为你这个两边是不一样的，你可以clone下来，新增一个drawable。

**Comment by helloShiTou11** [comment]
感谢作者，后续我先去研究了，后续有问题我在问您，发自内心的感谢

**Comment by sy007** [comment]
@HelloAnyu 你好，新版本已发布，支持了这个功能，可以去看下奥。
