### ISSUE TITLE
星期有没有办法设置从周一开始呢

### ISSUE THREAD

**Issue by liumengyue1992** [sy007/CalendarView#11]
如果星期顺序为从周一到周日显示，不是要修改drawDays里面的方法才行呢

**Comment by liumengyue1992** [comment]
感谢作者源码，看了下源码，这个问题挺好改的

**Comment by sy007** [comment]
> 
说来惭愧，想着一直重构，没时间:smile: ；找到就好

**Comment by sy007** [comment]
@liumengyue1992 新版本已发布，支持了月份从任意星期开始
