### ISSUE TITLE
范围不能滑动

### ISSUE THREAD

**Issue by mxdlsm** [sy007/CalendarView#12]
下载下来运行，为什么不能像图中那样范围区间可以向前或向后滑动

**Comment by sy007** [comment]
> 下载下来运行，为什么不能像图中那样范围区间可以向前或向后滑动

你好，范围区间是通过点击时间触发区间绘制的，不是通过滑动触发的；从录制的视频上是看不出来怎么触发的，周末视频替换下。

**Comment by sy007** [comment]
> 下载下来运行，为什么不能像图中那样范围区间可以向前或向后滑动

你好，范围区间是通过点击事件触发区间绘制的，不是通过滑动触发的；从录制的视频上是看不出来怎么触发的，周末视频替换下。
