### ISSUE TITLE
自定义属性rowheight类型定义不正确

### ISSUE THREAD

**Issue by zhongcg** [sy007/CalendarView#13]
rowHeight = ta.getFloat(R.styleable.MonthView_rowHeight, Util.dip2px(context, 64f)).toInt()  
        <attr name="rowHeight" format="dimension" />

**Comment by zhongcg** [comment]
values中定义<attr name="rowHeight" format="dimension" />

**Comment by zhongcg** [comment]
name="rowHeight" format="dimension"

**Comment by sy007** [comment]
@zhongcg 好的，感谢提醒，晚上修复下。

**Comment by sy007** [comment]
@zhongcg 你好问题已修复，请使用1.0.1版本
