### ISSUE TITLE
您好，能加下您的qq吗？我有个问题想咨询  1019132983 我的

### ISSUE THREAD

**Issue by yzxzm** [sy007/CalendarView#3]
怎样让今天之前的日期和最后选择的日期之后的不绘制出来？

**Comment by sy007** [comment]
你好，你说的是不绘制出来？如果几天是31号，那界面上前面的绘制的日期都空着，这也不太美观。同理最后选择的日期是1号，后面的都空着。本库是默认支持今天之前的日期不可选择，最后选择完日期可以选择性关掉页面或者弹窗，这是仿携程交互设计。不知道你现在需要做成什么样的效果？

**Comment by sy007** [comment]
@yzxzm 你好，你说的是不绘制出来？如果几天是31号，那界面上前面的绘制的日期都空着，这也不太美观。同理最后选择的日期是1号，后面的都空着。本库是默认支持今天之前的日期不可选择，最后选择完日期可以选择性关掉页面或者弹窗，这是仿携程交互设计。不知道你现在需要做成什么样的效果？

**Comment by sy007** [comment]
@yzxzm 后续规划会提供该功能。

**Comment by sy007** [comment]
@yzxzm 你还，新版本已支持这个功能，可以看下Simple的处理奥。

**Comment by sy007** [comment]
@yzxzm 你好，新版本已支持这个功能，可以看下Simple的处理奥。
