### ISSUE TITLE
怎么选择之前日期？而不是新日期？

### ISSUE THREAD

**Issue by JerryAlexLiang** [sy007/CalendarView#4]

**Comment by sy007** [comment]
@JerryAlexLiang 抱歉，目前没提供这样的功能。如需选择之前的日期需要修改源代码中getDayFromLocation#去掉isPreDay()函数判断应该就可以了。

**Comment by JerryAlexLiang** [comment]
> @JerryAlexLiang 抱歉，目前没提供这样的功能。如需选择之前的日期需要修改源代码中getDayFromLocation#去掉isPreDay()函数判断应该就可以了。

那请问 代码中怎样设置起始时间日期呢？谢谢

**Comment by JerryAlexLiang** [comment]
> 怎么选择之前日期？而不是新日期？
