### ISSUE TITLE
农历怎么添加

### ISSUE THREAD

**Issue by KevinLiu9527** [sy007/CalendarView#6]
项目中怎么添加显示农历

**Comment by sy007** [comment]
你好，目前只有把项目拉下来修改MonthView#covertAndSaveFestival 方法实现，在该方法中可以确定当前日期，你需要自己根据当前日期转换农历节日，并保存在festivalMap中

**Comment by sy007** [comment]
@KevinLiu9527 你好，目前只有把项目拉下来修改MonthView#covertAndSaveFestival 方法实现，在该方法中可以确定当前日期，你需要自己根据当前日期转换农历节日，并保存在festivalMap中。

**Comment by KevinLiu9527** [comment]
添加的农历，如何显示在数字日期下面，而不是显示在上面




| |
kevinliu9527
|
|
kevinliu9527@163.com
|
签名由网易邮箱大师定制
在2020年9月3日 17:47，SunYuan<notifications@github.com> 写道：

@KevinLiu9527 你好，目前只有把项目拉下来修改MonthView#covertAndSaveFestival 方法实现，在该方法中可以确定当前日期，你需要自己根据当前日期转换农历节日，并保存在festivalMap中。

**Comment by sy007** [comment]
您好，需要您调整MonthView#drawDays  内部canvas.drawText的顺序，本库默认是节日在上，日期在下，您可以clone下来自行调整。

**Comment by sy007** [comment]
@KevinLiu9527 新版本已发布，支持了农历节日展示，可以看下Simple的使用方式奥。
