### ISSUE TITLE
#bug 多次调用.display方法日历会不断下移

### ISSUE THREAD

**Issue by lzy-h2o2** [sy007/CalendarView#7]
多次调用.display方法日历会不断下移，应用场景：想在日历显示时同时支持单选和多选

**Comment by lzy-h2o2** [comment]
addItemDecoration(monthTitleDecoration);会重复添加，需要处理一下

**Comment by lzy-h2o2** [comment]
希望CalendarViewWrapper中增加在同一build中动态处理选中背景，用于适配同时支持单选和多选情况

        public CalendarBuilder setSelectBgFirst(Drawable selectBgFirst) {
            this.selectBgFirst = selectBgFirst;
            return this;
        }

        public CalendarBuilder setSelectBgLast(Drawable selectBgLast) {
            this.selectBgLast = selectBgLast;
            return this;
        }

**Comment by sy007** [comment]
感谢您的宝贵建议，就目前来说，如果您项目中存在这种动态切换的需求，还烦请您clone下来代码，自己修改下。修改方式正如您所说那样，display移除已添加的ItemDecoration，CalendarViewWrapper中增加同一build中动态处理选中背景并添加到ATTRS Map中。  本库很多功能未完善以及优化的地方，抽空会重写一版，包括您提出的建议。 @lzy-h2o2
