### ISSUE TITLE
日历选择日期后，再次点击如何有回显

### ISSUE THREAD

**Issue by sunyu1998** [sy007/CalendarView#8]
日历范围选择后，关闭日历，再次打开日历后如何显示之前选择的日期

**Comment by sy007** [comment]
@sunyu1998 
```
    //设置默认选中的日期
    .setCalendarSelectDay(calendarSelectDay)
    //选中模式-单选
    .setSelectionMode(SelectionMode.SINGLE)
```

改下这个选择模式，单选变为多选｜把你要回显的数据传递给`setCalendarSelectDay`。

**Comment by sunyu1998** [comment]
范围选择，回传一个开始时间，一个结束时间，我需要怎么传呢

**Comment by sy007** [comment]
兄弟，这是你自身业务逻辑的问题。你选中后记录下上次选择的日期，再次打开页面在调用`setCalendarSelectDay ` 之前将上次记录的日期设置进去不就行了嘛。
